#!/bin/bash

############################################################
# This is the main bootchain file                          #
#                                                          #
# The main things it does are:                             #
#                                                          #
#   1. Looks for bootstrap scripts between itself and      #
#      target                                              #
#   2. Executes these bootstraps pseudo-recursively        #
#                                                          #
#   Usage: ./bootstrap.sh mytest mytest2 mytest3           #
#                                                          #
############################################################





# Configuration
bootstrap_file_name="bootstrap"            # extensions are omitted
bootchain_log="chain.log"
fifo_file="/tmp/bootchain_child_to_parent" # the fifo file used by children to send info
vars_file="/tmp/bootchain_vars"

# Traps
trap "CHILD_SUSPENDED=true" SIGCONT
trap "cleanup" EXIT

# Init
function init () {
	CHILD_SUSPENDED=false
	LAST_CHILD=false
	mkfifo -m a=rw "$fifo_file"
}
init

# Cleanup
function cleanup () {
	rm -f "$vars_file"
	rm -f "$fifo_file"
}



#=======================================================================
#                          Public Interface
#=======================================================================
# These functions run inside the child process - no access to parent vars


#=============================== API ===================================

export_var () { #var_name #var_value
	echo "$1"'='\""$2"\" >> "$vars_file"
}
export vars_file
export -f export_var

export LAST_CHILD
bootstrap_wait () {
   trap "exit_handler" EXIT
	if ! $LAST_CHILD
	then
		suspend_me
		read_fifo
	fi
}
export -f bootstrap_wait

export fifo_file

#=========================== used by child =============================


# Makes sure we know if user invoked exit explicitly
# Needs a trap to EXIT to work
exit_handler () {
   ret=$?
   if echo "$BASH_COMMAND" | grep -e "^exit \|^exit$" >> /dev/null
   then
      echo "it was an explicit exit"
      # THUS WE SHOULD UPDATE RETURN VALUE
      RETURN_VALUE=$ret
   else
      echo "it was an implicit exit"
      # WE SHOULDN'T DO ANYTHING HERE, LET RETURN VALUE PROPAGATE
   fi
   write_fifo $ret
   exit $ret
}
export -f exit_handler


suspend_me () {
	trap 'SUSPEND=false' SIGCONT
	SUSPEND=true
	kill -SIGCONT "$PPID" # tell parent that we reached suspend state
	while $SUSPEND
	do
		sleep 0.1
	done;
}
export -f suspend_me


set_return_value () { #value
	#RETURN_VALUE="$1"
	#trap "exit $RETURN_VALUE" EXIT
   echo
}
export -f set_return_value


#=======================================================================
#                     Interprocess communication
#=======================================================================
#
# !!! Signals are used to synchronise parent and children !!!
#
#

spawn_child () { #path_to_script
	if [ "$bootstrap" == "$last_bootstrap" ]
	then
		LAST_CHILD=true
	fi
	export LAST_CHILD
	
	export_vars

	cd `dirname "$1"`
	'./'"$bootstrap_file_name" &
	cd "$OLDPWD"
}

kill_and_wait () { #pid #signal 
	local signal='SIGINT'
	if (( $# > 1 )); then
		signal=$2
	fi
	kill -$signal $1
	wait $1
}

resume_child () { #child_pid
	kill_and_wait "$1" SIGCONT
}

write_fifo () { #string
   echo "write_fifo ($BASHPID)"
   echo "$1" > "$fifofile"
}
export -f write_fifo

read_fifo () {
   echo "read_fifo ($BASHPID)"
   cat "$fifo_file"
}
export -f read_fifo

# This will export all variables found in $vars_file
export_vars () {
	if ! ls "$vars_file" &>> /dev/null; then
		return; fi
	old_IFS=$IFS
	IFS=$'\n'
	for line in `cat "$vars_file"`
	do
		source "$vars_file"
		local var=`echo "$line" | cut -f1 -d'='`
		local val=`echo "$line" | cut -f2 -d'='`
		export "$var"
	done
	IFS=$old_IFS
}


#=======================================================================
#                        Generic functions
#=======================================================================

function len { #string
   echo ${#1}
}

function count_char { #string #char
   len $( echo "$1" | tr -d -c "$2\n" )
}



# All possible paths excluding . and ..
function all_paths { #path
	local paths_N=`count_char "$1" '/'`
	for i in `seq $paths_N`
	do
		local path=`echo "$1" | cut -d'/' -f1-"$i"`
		if [ `echo "$1" | cut -b1` == '.' ] && [ `len "$path"` == '1' ]
		then
			continue #omit current path
		fi
		if [ ! "$paths" ]; then
			local paths="$path"
		else
			local paths="$paths $path"
		fi
	done
	echo "$paths"
}

function last_path { #paths
	echo `echo "$1" | sed 's/.* //'`
}

function count_paths { #paths
	echo "$1" | tr -d -c ' ' | awk '{ print length+1 }'
}

function pid_exists { #pid
	ps -p "$1" >> /dev/null
}


#=======================================================================
#                         Bootstrap functions
#=======================================================================

function has_bootstrap_wait { #bootstrap_path
	if grep -e '^bootstrap_wait$' "$1" >> /dev/null
	then
		true
	else
		false
	fi
}

function all_bootstraps { #path
	paths='. '`all_paths "$1"`
	bootstraps=''
	for path in `echo "$paths"`
	do
		if ls "$path/$bootstrap_file_name" &> /dev/null
		then
			bootstraps+=" $path/$bootstrap_file_name"
		fi
	done
	echo "$bootstraps"
}


#=======================================================================
#                               Usage
#=======================================================================

function usage {
	echo "Usage: `basename $0` <testfile> <testfile2> .."
	echo "       where <testfile1>, etc. are the pathnames"
	echo "       to the test files"
}



#=======================================================================
#                               Intro
#=======================================================================

echo
echo "   _________________________________________________ "
echo "  |    ___     ___                   ___            |"
echo "  |   |  /    |  /     Bootchain     \  |           |"
echo "  |---| (__---| (__-----------------__) |           |"
echo "  |   (____)  (____)               (____)           |"
echo "  |_________________________________________________|"
echo

if (($# == 0)); then
	echo "No tests given."
	echo "Exiting."
	usage
	exit 0
fi



#=======================================================================
#                               Main
#=======================================================================

# Fixate bootstrap naming
if [ `count_char "bootstrap_file_name" '.'` -lt 0 ]; then
	bootstrap_file_name=`echo "$bootstrap_file_name" | cut -f1 -d'.'`
fi


# Run specified test in it
echo
echo "Will run targets.."

for target in "$@"
do

	# Does target exist?
	if ! ls "$target" > /dev/null
	then
		echo "ERROR: Target doesn't exist: $target"
		exit 1
	fi
	
	# Set vars
	TARGET_PATH=$target
	TARGET=`basename $target`
	export TARGET_PATH
	export TARGET
	rm -f "$vars_file"
	
	echo "-------------------------------------------------------------"  
	echo "Target: $target"
	
	children=()           # holds all created children
	suspended_children=() # holds only suspended children
	
	bootstraps=`all_bootstraps "$target"`
	last_bootstrap=`last_path "$bootstraps"`
	
	# Run sibling + suspended_children bootstraps (order is important)
	for bootstrap in `echo "$bootstraps"`
	do

		# Spawn child
		spawn_child "$bootstrap"
		pid=$!
		children+=($pid)

		# Should it wait?
		if has_bootstrap_wait "$bootstrap" && [ "$bootstrap" != "$last_bootstrap" ]
		then
			suspended_children+=($!)
			while ! $CHILD_SUSPENDED
			do
				sleep 0.01
			done
			CHILD_SUSPENDED=false
		elif [ "$bootstrap" != "$last_bootstrap" ]
		then
			wait $pid
		fi
		

	done
	
	
	# Wait for last bootstrap to exit
	wait ${children[@]:(-1)}
	RETURN_VALUE="$?"
	LAST_CHILD=false

	# Returning value to prev child
	rm -f "$fifo_file"
	mkfifo -m a=rw "$fifo_file"
	echo "$RETURN_VALUE" > "$fifo_file" &

	# Exit suspended bootstraps gradually in a LIFO fashion
	for (( i=${#suspended_children[@]}-1 ; i>=0 ; i-- ))
	do
		child="${suspended_children[i]}"
		if pid_exists "$child"
		then
			
         
        #RETURN_VALUE=
         
		# Write return value to fifo for child to read
        # SOMEHOW UPDATE RETURN VALUE
        # THUS PARENT MUST KNOW IF EXPLICIT
        read_fifo
			
		# Then resume
		resume_child "$child"
        echo sigcontinue "$child"
         
        #RETURN_VALUE=$?
		fi
	done

done
